2024-06-22 22:11:52,105 INFO    StreamThr :11752 [internal.py:wandb_internal():85] W&B internal server running at pid: 11752, started at: 2024-06-22 22:11:52.104948
2024-06-22 22:11:52,107 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: status
2024-06-22 22:11:52,110 INFO    WriterThread:11752 [datastore.py:open_for_write():87] open: C:\Users\30533\Desktop\Pytorch-UNet-master\wandb\run-20240622_221152-mnlyxf53\run-mnlyxf53.wandb
2024-06-22 22:11:52,112 DEBUG   SenderThread:11752 [sender.py:send():379] send: header
2024-06-22 22:11:52,118 DEBUG   SenderThread:11752 [sender.py:send():379] send: run
2024-06-22 22:11:52,121 INFO    SenderThread:11752 [sender.py:_setup_resume():749] checking resume status for None/U-Net/mnlyxf53
2024-06-22 22:11:56,307 INFO    SenderThread:11752 [retry.py:__call__():172] Retry attempt failed:
urllib3.exceptions.SSLError: TLS/SSL connection has been closed (EOF) (_ssl.c:1135)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1135)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\U-net\lib\site-packages\requests\adapters.py", line 589, in send
    resp = conn.urlopen(
  File "D:\Anaconda3\envs\U-net\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "D:\Anaconda3\envs\U-net\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1135)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\U-net\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Anaconda3\envs\U-net\lib\site-packages\wandb\sdk\internal\internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\Anaconda3\envs\U-net\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Anaconda3\envs\U-net\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Anaconda3\envs\U-net\lib\site-packages\wandb\sdk\lib\gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "D:\Anaconda3\envs\U-net\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\Anaconda3\envs\U-net\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda3\envs\U-net\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda3\envs\U-net\lib\site-packages\requests\adapters.py", line 616, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1135)'))))
2024-06-22 22:11:57,150 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:12:02,172 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:12:07,377 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:12:12,399 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:12:17,433 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:12:22,464 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:12:27,510 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:12:32,534 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:12:37,553 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:12:42,585 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:12:47,615 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:12:52,644 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:12:57,663 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:13:02,779 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:13:07,818 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:13:12,860 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:13:17,899 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: keepalive
2024-06-22 22:13:22,961 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: cancel
2024-06-22 22:13:22,961 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: cancel
2024-06-22 22:13:22,962 DEBUG   SenderThread:11752 [sender.py:send():388] Record cancelled: run
2024-06-22 22:13:22,962 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: status_report
2024-06-22 22:13:24,631 DEBUG   HandlerThread:11752 [handler.py:handle_request():158] handle_request: shutdown
2024-06-22 22:13:24,631 INFO    HandlerThread:11752 [handler.py:finish():882] shutting down handler
2024-06-22 22:13:24,976 INFO    WriterThread:11752 [datastore.py:close():296] close: C:\Users\30533\Desktop\Pytorch-UNet-master\wandb\run-20240622_221152-mnlyxf53\run-mnlyxf53.wandb
2024-06-22 22:13:24,976 INFO    SenderThread:11752 [sender.py:finish():1608] shutting down sender
